### ISSUE TITLE
potential sigterm/sigkill scenarios

### ISSUE THREAD

**Issue by adrianpowierza** [jasonwvh/webhook-handler#1]
Hello, @jasonwvh!

thanks for doing our trial project! We like your submission and we're curious about some additional tests. We'd like to check two scenarios:
- App received sigkill when processing data. Does it recover&continue when up again?
- App received sigterm. Does it shutdown gracefully?

Could you prepare those two? It would be perfect to make it as PR instead of direct write to master :)

Remember you can ask any question you want!

**Comment by jasonwvh** [comment]
Hey @adrianpowierza, thanks for the question. Currently the app isn't built to handle signals (it will shut down immediately) but I can create a PR for that. 

That being said, it is built to handle failed messages. We can simply change the `auto-ack` to false (I set it to true for development purposes) and `Ack()` it manually after the processing is done. If the app is shut down during the processing, the message gets picked up again when it is restart.

**Comment by adrianpowierza** [comment]
Thanks for explanation. I think you can apply those two - if it's not too big concern of course

**Comment by jasonwvh** [comment]
Of course, please allow me some time to work on it

**Comment by adrianpowierza** [comment]
Thanks for provided solution!
