### ISSUE TITLE
A challange requirements 

### ISSUE THREAD

**Issue by adrianpowierza** [jasonwvh/webhook-handler#3]
Hello, @jasonwvh. I spot major issue with provided solution. What are possible fixes?

### Requirement
A work item consists of a json payload that includes a numeric identifier, and a URL. To simulate work, we add a 1 second sleep in the handler. We require the service to A) acknowledge work items < 1 second.

### Test result
It seems like any of webhook can process the request:
- sync processes slower than 1s
- async accepts pretty quick, but doesn't process all requests (only 2 of them is processed). I checked via db (2 records) and added log near url call

### Test using sync webhook
```
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/webhook -X POST -d '{"id":1,"url":"http://google.com","seq":1}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/webhook -X POST -d '{"id":2,"url":"http://google.com","seq":2}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/webhook -X POST -d '{"id":3,"url":"http://google.com","seq":3}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/webhook -X POST -d '{"id":4,"url":"http://google.com","seq":4}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/webhook -X POST -d '{"id":5,"url":"http://google.com","seq":5}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/webhook -X POST -d '{"id":6,"url":"http://google.com","seq":6}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/webhook -X POST -d '{"id":7,"url":"http://google.com","seq":7}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/webhook -X POST -d '{"id":8,"url":"http://google.com","seq":8}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/webhook -X POST -d '{"id":9,"url":"http://google.com","seq":9}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/webhook -X POST -d '{"id":10,"url":"http://google.com","seq":10}'
Total: 1.167987s
Total: 1.128217s
Total: 1.110811s
Total: 1.506620s
Total: 1.121112s
Total: 1.113819s
Total: 1.124903s
Total: 1.123070s
Total: 1.151900s
Total: 1.118618s
```

### Test using async webhook
```
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/async-webhook -X POST -d '{"id":1,"url":"http://google.com","seq":1}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/async-webhook -X POST -d '{"id":2,"url":"http://google.com","seq":2}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/async-webhook -X POST -d '{"id":3,"url":"http://google.com","seq":3}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/async-webhook -X POST -d '{"id":4,"url":"http://google.com","seq":4}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/async-webhook -X POST -d '{"id":5,"url":"http://google.com","seq":5}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/async-webhook -X POST -d '{"id":6,"url":"http://google.com","seq":6}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/async-webhook -X POST -d '{"id":7,"url":"http://google.com","seq":7}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/async-webhook -X POST -d '{"id":8,"url":"http://google.com","seq":8}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/async-webhook -X POST -d '{"id":9,"url":"http://google.com","seq":9}'
curl -o /dev/null -s -w 'Total: %{time_total}s\n' localhost:8080/async-webhook -X POST -d '{"id":10,"url":"http://google.com","seq":10}'
Total: 0.002500s
Total: 0.001189s
Total: 0.001353s
Total: 0.001253s
Total: 0.001141s
Total: 0.001419s
Total: 0.001308s
Total: 0.001640s
Total: 0.001293s
Total: 0.001344s
```
result from logs:
```
backend   | Server running on port 8080
backend   | 2024/04/17 09:51:06 Received a message: {"id":1,"url":"http://google.com","seq":1} with retry 0
backend   | 2024/04/17 09:51:06 Received a message: {"id":2,"url":"http://google.com","seq":2} with retry 0
backend   | 2024/04/17 09:51:06 Received a message: {"id":3,"url":"http://google.com","seq":3} with retry 0
backend   | 2024/04/17 09:51:06 Received a message: {"id":4,"url":"http://google.com","seq":4} with retry 0
backend   | 2024/04/17 09:51:06 Received a message: {"id":5,"url":"http://google.com","seq":5} with retry 0
backend   | 2024/04/17 09:51:06 Received a message: {"id":6,"url":"http://google.com","seq":6} with retry 0
backend   | 2024/04/17 09:51:06 Received a message: {"id":7,"url":"http://google.com","seq":7} with retry 0
backend   | 2024/04/17 09:51:06 Received a message: {"id":8,"url":"http://google.com","seq":8} with retry 0
backend   | 2024/04/17 09:51:06 Received a message: {"id":9,"url":"http://google.com","seq":9} with retry 0
backend   | 2024/04/17 09:51:06 Received a message: {"id":10,"url":"http://google.com","seq":10} with retry 0
backend   | Processing work item 1
backend   | Processing work item 2
backend   | 2024/04/17 09:51:11 Received a message: {"id":3,"url":"http://google.com","seq":3} with retry 1
backend   | 2024/04/17 09:51:11 Received a message: {"id":4,"url":"http://google.com","seq":4} with retry 1
backend   | 2024/04/17 09:51:11 stored item: &{1 http://google.com 1}
backend   | 2024/04/17 09:51:11 stored item: &{2 http://google.com 2}
backend   | 2024/04/17 09:51:16 Received a message: {"id":5,"url":"http://google.com","seq":5} with retry 1
backend   | 2024/04/17 09:51:16 Received a message: {"id":6,"url":"http://google.com","seq":6} with retry 1
backend   | 2024/04/17 09:51:16 Received a message: {"id":7,"url":"http://google.com","seq":7} with retry 1
backend   | 2024/04/17 09:51:16 Received a message: {"id":8,"url":"http://google.com","seq":8} with retry 1
backend   | 2024/04/17 09:51:21 Received a message: {"id":9,"url":"http://google.com","seq":9} with retry 1
backend   | 2024/04/17 09:51:21 Received a message: {"id":10,"url":"http://google.com","seq":10} with retry 1
backend   | 2024/04/17 09:51:21 Received a message: {"id":3,"url":"http://google.com","seq":3} with retry 2
backend   | 2024/04/17 09:51:21 Received a message: {"id":4,"url":"http://google.com","seq":4} with retry 2
backend   | 2024/04/17 09:51:26 Received a message: {"id":5,"url":"http://google.com","seq":5} with retry 2
backend   | 2024/04/17 09:51:26 Received a message: {"id":6,"url":"http://google.com","seq":6} with retry 2
backend   | 2024/04/17 09:51:26 Received a message: {"id":7,"url":"http://google.com","seq":7} with retry 2
backend   | 2024/04/17 09:51:26 Received a message: {"id":8,"url":"http://google.com","seq":8} with retry 2
backend   | 2024/04/17 09:51:31 Received a message: {"id":9,"url":"http://google.com","seq":9} with retry 2
backend   | 2024/04/17 09:51:31 Received a message: {"id":10,"url":"http://google.com","seq":10} with retry 2
backend   | 2024/04/17 09:51:31 Received a message: {"id":3,"url":"http://google.com","seq":3} with retry 3
backend   | 2024/04/17 09:51:31 Received a message: {"id":4,"url":"http://google.com","seq":4} with retry 3
backend   | 2024/04/17 09:51:36 Received a message: {"id":5,"url":"http://google.com","seq":5} with retry 3
backend   | 2024/04/17 09:51:36 Received a message: {"id":6,"url":"http://google.com","seq":6} with retry 3
backend   | 2024/04/17 09:51:36 Received a message: {"id":7,"url":"http://google.com","seq":7} with retry 3
backend   | 2024/04/17 09:51:36 Received a message: {"id":8,"url":"http://google.com","seq":8} with retry 3
backend   | 2024/04/17 09:51:41 Received a message: {"id":9,"url":"http://google.com","seq":9} with retry 3
backend   | 2024/04/17 09:51:41 Received a message: {"id":10,"url":"http://google.com","seq":10} with retry 3
// EOF
```

**Comment by jasonwvh** [comment]
Hi @adrianpowierza, just wanted to make sure I understand everything correctly.

```To simulate work, we add a 1 second sleep in the handler. ```
There's a `time.Sleep(1 * time.Second)` in the handler to processing of item.

```We require the service to A) acknowledge work items < 1 second.``` 
We can change handler to respond 200 OK as soon as the checks pass.

But...

``` our service MUST NOT reply with an OK if there is any doubt the work item isn’t recorded or may get lost on our side.```
The app responds a 200 OK only after it has done processing it (hence the 1 second delay)

**Comment by jasonwvh** [comment]
For the `async`, it mainly comes from the Part B challenge. I didn't have a solution to handle the `sequence` with strong consistency, i.e. must be in order 1, 2, 3, ...

I will remove the check for now.

**Comment by adrianpowierza** [comment]
> Hi @adrianpowierza, just wanted to make sure I understand everything correctly.
> 
> `To simulate work, we add a 1 second sleep in the handler. ` There's a `time.Sleep(1 * time.Second)` in the handler to processing of item.
> 
> `We require the service to A) acknowledge work items < 1 second.` We can change handler to respond 200 OK as soon as the checks pass.
> 
> But...
> 
> ` our service MUST NOT reply with an OK if there is any doubt the work item isn’t recorded or may get lost on our side.` The app responds a 200 OK only after it has done processing it (hence the 1 second delay)

I think there's some misunderstanding here. We want to accept records as soon as possible and validate if the request is ok (validate url, save record/push to message queue), but handle url calls async (to not block the webhook).

Just to make sure:
Challange A doesn't care about seqid and use FIFO processing. Challange B is about ordered processing by seqid

**Comment by jasonwvh** [comment]
Ok my apologies. I assumed there was a `sync` and an `async` handler based on this comment:
> We encourage the use of an executor pattern and would like to see an asynchronous handler in the real world, and a synchronous handler in at least one unit test for demonstration.

> We want to accept records as soon as possible and validate if the request is ok

This is handled by the `async` handler

> Challange A doesn't care about seqid and use FIFO processing. Challange B is about ordered processing by seqid

Yeah, it had no problem handling Challenge A. The app broke after I attempted Challenge B.

#### Problem
The root cause is that the app was handling the request `in parallel` with multiple workers, with the additional challenge of `in-order processing`

It had no problem handling Challenge A, but breaks under Challenge B.

#### Quick Fix
I see two possible quick fixes:
- Remove `in-order processing`, or
- Scale worker to `1`

**Comment by adrianpowierza** [comment]
No worries at all. IMO we can try to accomplish challenge A part (accept/validate asap, call url later with 1 sec sleep) and drop challange B at this point to not extend time spend on project. WDYT?

**Comment by jasonwvh** [comment]
Of course. Thanks, I'll raise a PR for the fix briefly.

**Comment by jasonwvh** [comment]
Actually, I already commented out the challenge B in the last PR. 

`/async-webhook` should be able to process multiple work items quickly now.

**Comment by jasonwvh** [comment]
on the other hand, the sync `/webhook` still handles the `SeqID` in order (solves part B), but because of the 1 second delay, the response is always >1s. If we remove the 1 second delay, it's actually pretty fast.

**Comment by adrianpowierza** [comment]
> on the other hand, the sync /webhook still handles the SeqID in order (solves part B), but because of the 1 second delay, the response is always >1s. If we remove the 1 second delay, it's actually pretty fast.

We don't have guarantee that url call is quick. We don't know what is the url (google.com is only example). It can be any url and we intentionally slow down the handler to show that. We also don't have guarantee if 3rd party waits for the response before calling again (race condition can happen)

> Actually, I already commented out the challenge B in the last PR.
> /async-webhook should be able to process multiple work items quickly now.

### Retest
```
curl localhost:8080/async-webhook -X POST -d '{"id":1,"url":"http://google.com","seq":1}' \
& curl localhost:8080/async-webhook -X POST -d '{"id":2,"url":"http://google.com","seq":2}' \
& curl localhost:8080/async-webhook -X POST -d '{"id":3,"url":"http://google.com","seq":3}' \
& curl localhost:8080/async-webhook -X POST -d '{"id":4,"url":"http://google.com","seq":4}' \
& curl localhost:8080/async-webhook -X POST -d '{"id":5,"url":"http://google.com","seq":5}' \
& curl localhost:8080/async-webhook -X POST -d '{"id":6,"url":"http://google.com","seq":6}' \
& curl localhost:8080/async-webhook -X POST -d '{"id":7,"url":"http://google.com","seq":7}' \
& curl localhost:8080/async-webhook -X POST -d '{"id":8,"url":"http://google.com","seq":8}' \
& curl localhost:8080/async-webhook -X POST -d '{"id":9,"url":"http://google.com","seq":9}' \
& curl localhost:8080/async-webhook -X POST -d '{"id":10,"url":"http://google.com","seq":10}'
```

### Result
9/10 accepted quick. One wasn't created with "work item pending" error. Seems like id=1 is a trouble

**Comment by jasonwvh** [comment]
you're right, that's an odd behavior, let me look into it

**Comment by adrianpowierza** [comment]
retested after https://github.com/jasonwvh/webhook-handler/pull/4. All created fine 🎉 

I'd like to ask one more question - why do we need redis for challenge A?

**Comment by jasonwvh** [comment]
Nice!

Redis was added mainly to reject duplicate requests. 

If the application suddenly receives 100 of the same request (same ID), only the first 1 will be recorded, and the next 99 will dropped. Without Redis, all 100 duplicate requests would be redirected to RabbitMQ and subsequently our consumer. 
Even though the database will still only accept 1, it is still unnecessary load on our system that we can prevent.

It also fulfills the following condition by returning a 409 instead of a 200 as quick as possible:
> our service MUST NOT reply with an OK if there is any doubt the work item isn’t recorded or may get lost on our side.

**Comment by adrianpowierza** [comment]
I see that's good. I wonder if there's any way to reduce tech-stack and achieve the same without redis?

**Comment by jasonwvh** [comment]
There were 2 alternatives that I considered before deciding on Redis.

1. We can just use the database
Pros: Simpler tech stack
Cons: SQLite is fast enough to keep a cache since it's just local I/O. But in a production setting, we won't be using SQLite. Redis will be faster than a production database such as MySQL.

2. We can just keep a list in-memory
Pros: Much faster than Redis, and simpler
Cons: This won't work in the case that there's multiple instance of the backend, such as running multiple replicas in Kubernetes. 

For a simple monolith use case, Option 2 is good enough. Redis is only here to highlight the potential issue we may face in a production setting.

**Comment by adrianpowierza** [comment]
I like it. Thanks for explanation!
